name: Postman API Tests

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:
  newman-api-test:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout Code
        uses: actions/checkout@v4

      - name: Install Node.js
        uses: actions/setup-node@v4
        with:
          node-version: '20'

      - name: Install Newman and Reporter
        run: |
          npm install newman newman-reporter-htmlextra

      - name: Run API Tests with Newman
        id: run-newman
        run: |
          echo "üìå Starting Newman test..."
          TIMESTAMP=$(date +'%Y-%m-%d-%H-%M-%S')
          REPORT_NAME="Postman-Report-${TIMESTAMP}.html"
          
          npx newman run "postman-tests/AutomateTest_postman_collection.json" \
            -e "postman-tests/reqres-api.postman_environment.json" \
            -r htmlextra \
            --reporter-htmlextra-export "$REPORT_NAME"
          
          echo "exit_code=$?" >> $GITHUB_OUTPUT
          echo "report_name=$REPORT_NAME" >> $GITHUB_OUTPUT

      - name: Upload Postman Report
        if: always()
        uses: actions/upload-artifact@v4
        with:
          name: postman-html-report
          path: ${{ steps.run-newman.outputs.report_name }}

      - name: Fail job if Newman failed
        if: always() && steps.run-newman.outputs.exit_code != '0'
        run: |
          echo "‚ùå Newman tests failed with exit code ${{ steps.run-newman.outputs.exit_code }}"
          exit 1