name: Postman API Tests

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:
  newman-api-test:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout Code
        uses: actions/checkout@v4

      - name: Install Node.js
        uses: actions/setup-node@v4
        with:
          node-version: '20'

      - name: Install Newman and Reporter
        run: |
          npm install  newman
          npm install  newman-reporter-htmlextra

      - name: Run API Tests with Newman
        id: run-newman
        run: |
          set -x
          echo "üìå Starting Newman test..."
          TIMESTAMP=$(date +'%Y-%m-%d-%H-%M-%S')
          REPORT_NAME="Postman-Report-${TIMESTAMP}.html"
          
          set +e
          # ‡∏£‡∏±‡∏ô Newman ‡πÇ‡∏î‡∏¢‡∏ä‡∏µ‡πâ‡πÑ‡∏õ‡∏ó‡∏µ‡πà‡πÑ‡∏ü‡∏•‡πå‡πÉ‡∏ô‡πÇ‡∏ü‡∏•‡πÄ‡∏î‡∏≠‡∏£‡πå postman-tests (‡∏ï‡∏≤‡∏°‡∏ó‡∏µ‡πà‡πÄ‡∏´‡πá‡∏ô‡∏à‡∏≤‡∏Å path CMD ‡∏Ç‡∏≠‡∏á‡∏Ñ‡∏∏‡∏ì)
          newman run "postman-tests/AutomateTest_postman_collection.json" \
            -e "postman-tests/reqres-api.postman_environment.json" \
            -r htmlextra \
            --reporter-htmlextra-export "${REPORT_NAME}"
          
          CODE=$?
          set -e

          echo "report_name=${REPORT_NAME}" >> $GITHUB_OUTPUT
          echo "exit_code=${CODE}" >> $GITHUB_OUTPUT
          exit 0

      - name: Upload Postman Report
        if: always()
        uses: actions/upload-artifact@v4
        with:
          name: postman-html-report
          path: ${{ steps.run-newman.outputs.report_name }}

      - name: Fail job if Newman failed
        if: ${{ steps.run-newman.outputs.exit_code != '0' }}
        run: |
          echo "‚ùå Newman tests failed. Failing the job."
          exit 1